server:
  port: 3003
  address: 0.0.0.0  # Bind to all network interfaces

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: enrollment_service
  mvc:
    cors:
      mapping: "/**"
      allowed-origins: 
        - http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
      exposed-headers: Authorization

jwt:
  secret: QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=
  expiration: 3600000  # 1 hour in milliseconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50 