spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongodb}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:enrollment_service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address:localhost}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

# JWT configuration
jwt:
  secret: ${JWT_SECRET:QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=}
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hour in milliseconds

# Health check configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true