server:
  port: 8761
  address: 0.0.0.0  # Bind to all network interfaces

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    # Enable self-preservation but with lower threshold
    enable-self-preservation: true
    # Lower renewal threshold to 60% for more aggressive expiry
    renewal-percent-threshold: 0.60
    # More frequent eviction checks
    eviction-interval-timer-in-ms: 15000
    # Faster response cache updates
    response-cache-update-interval-ms: 15000
    # Shorter lease expiration
    lease-expiration-duration-in-seconds: 15
    # More frequent renewals
    lease-renewal-interval-in-seconds: 5
    # Additional settings for better instance management
    renewal-threshold-update-interval-ms: 10000
    expected-client-renewal-interval-seconds: 5 